version: "3"
services:
    adminer:
        image: adminer:latest
        restart: unless-stopped
        ports:
            - 8000:8080
    db:
        image: postgres:latest
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: toor
            POSTGRES_DB: panel
